version: '3'
services:

    db:
      container_name: postgres-container
      image: postgres
      environment:
        POSTGRES_DB: [dbname]
        POSTGRES_USER: [username]
        POSTGRES_PASSWORD: [password]
      ports:
        - "5430:5432"
        # (HOST:CONTAINER)
      volumes:
        - pgdata:/var/lib/postgresql/data/

    nginx:
        container_name: nginx-container        
        build: ./nginx
        restart: always
        ports:
        - "80:80"
        volumes:        
        - ./app:/docker_app
        - ./log:/var/log/nginx              
        depends_on:
        - app
        
    app:
        container_name: app-container
        build: ./app
        restart: always
        # command: uwsgi  --emperor uwsgi.ini         
        command: uwsgi --ini uwsgi.ini
        ports:
        - "8002:8000"
        volumes:
        - ./app:/docker_app
        depends_on:
        - db

volumes:
    pgdata: