version: '3'
services:

    db:
      container_name: postgres-container
      image: postgres
      environment:
        POSTGRES_PASSWORD: password123
      ports:
        - "5430:5432"
        # (HOST:CONTAINER)
      volumes:
        - pgdata:/var/lib/postgresql/data/

    nginx:
        container_name: nginx-container        
        build: ./nginx
        restart: always
        ports:
        - "8080:80" 
        volumes:        
        - app_data:/docker_app
        - ./log:/var/log/nginx              
        depends_on:
        - app
        
    app:
        container_name: app-container
        build: ./app
        restart: always
        # command: uwsgi  --emperor uwsgi.ini         
        command: uwsgi --ini uwsgi.ini
        ports:
        - "8002:8000"
        volumes:
        - app_data:/docker_app
        depends_on:
        - db

volumes:
    pgdata:
    app_data:
